# -*- coding: utf-8 -*-
"""Line segment intersections visualizations.ipynb

Automatically generated by Colaboratory.
@author R ADARSH 
Original file is located at
    https://colab.research.google.com/drive/1u6XlbDC-OLENzHRagBbOerDqhPoeQN97
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re

x_start = []
y_start = []
x_end = []
y_end = []
pts_x = []
pts_y = []

fname1 = input("Enter path of file containing segments : ")
fname2 = input("Enter path of file containing intersections : ")
file1 = open(fname1, 'r')
Lines = file1.readlines()
file2 = open(fname2,'r')
Lines1 = file2.readlines()
count = 0
# Strips the newline character
for line in Lines:
    x_start.append(float(line.split()[0]))
    y_start.append(float(line.split()[1]))
    x_end.append(float(line.split()[2]))
    y_end.append(float(line.split()[3]))

for line in Lines1:
    pts_x.append(float(line.split()[0]))
    pts_y.append(float(line.split()[1]))

for i in range(len(x_start)):
  plt.plot([x_start[i],x_end[i]],[y_start[i],y_end[i]], 'r', linewidth=2)
  plt.plot(pts_x, pts_y,marker='o', markerfacecolor='yellow', markersize=7,linewidth=0)

fig_name=fname2.split('\\')[-1].split('.')[0].split('_')[-1]
plt.savefig("C:\\Users\\BITS-PC\\Desktop\\DAA Assignment\\Line intersection\\Line arrangement visualisations\\dig"+fig_name+".png")
plt.show()


